import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";

test("app renders solver controls, canvases, and output metrics", async ({ page }) => {
  const pageErrors: string[] = [];
  page.on("pageerror", (error) => pageErrors.push(error.message));
  await page.goto("/wizard_of_oz.html");
  await expect(page.getByRole("heading", { name: "OZwizard" })).toBeVisible();
  await expect(page.getByAltText("OZwizard logo")).toBeVisible();
  await expect(page.getByAltText("OZwizard logo")).toHaveJSProperty("naturalWidth", 498);
  await expect(page.getByRole("button", { name: "RK45" })).toHaveClass(/active/);
  await expect(page.locator("#solverButtons button")).toHaveCount(3);
  await expect(page.locator("#presetButtons")).not.toBeVisible();
  await expect(page.locator("#presetSummaryLabel")).toContainText("RR Lyrae low-amplitude fundamental, damped");
  await page.locator("#presetPanel summary").click();
  await expect(page.locator("#presetButtons")).toBeVisible();
  await expect(page.getByRole("button", { name: "RR Lyrae low-amplitude fundamental, damped" })).toHaveClass(/active/);
  await expect(page.getByRole("button", { name: "Baker radiative pulsator" })).toBeVisible();
  await expect(page.getByRole("button", { name: "RR Lyrae first overtone", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "RR Lyrae first overtone, damped" })).toBeVisible();
  await expect(page.getByRole("button", { name: "RR Lyrae high-amplitude first overtone" })).toBeVisible();
  await expect(page.getByRole("button", { name: "RR Lyrae low-amplitude fundamental, damped" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Local radiative OZ1" })).toBeVisible();
  await expect(page.getByRole("button", { name: /corrected/i })).toHaveCount(0);
  await expect(page.getByLabel("Compare selected solver to midpoint")).toHaveCount(0);
  await expect(page.locator("#runUntilStable")).not.toBeChecked();
  const physicalControlsBox = await page.locator("#physicalControls").boundingBox();
  const geometryBox = await page.locator("#variableM").boundingBox();
  const driverBox = await page.locator("[data-driver='h']").boundingBox();
  expect(physicalControlsBox).not.toBeNull();
  expect(geometryBox).not.toBeNull();
  expect(driverBox).not.toBeNull();
  expect(physicalControlsBox!.y).toBeLessThan(geometryBox!.y);
  expect(geometryBox!.y).toBeLessThan(driverBox!.y);
  await expect(page.locator("#statusPill")).toContainText("stop:");
  await expect(page.locator("#metrics")).toContainText("models");
  await expect(page.locator("#metrics")).not.toContainText("stop reason");
  await expect(page.locator("#metrics")).not.toContainText("reference");
  await expect(page.locator("#metrics")).not.toContainText("driver");
  await expect(page.locator("#metrics")).not.toContainText("solver");
  await expect.poll(async () => (await page.locator("body").innerText()).includes("\\(")).toBe(false);

  const canvases = page.locator("canvas");
  await expect(canvases).toHaveCount(4);
  const tauCell = page.locator("[data-symbol='tau']").first();
  const tauRow = tauCell.locator("xpath=ancestor::tr");
  await expect(tauCell).toBeVisible();
  await expect(tauRow).toContainText("free-fall/dynamical time");
  await expect(tauCell).toHaveCSS("color", "rgb(158, 167, 255)");
  await expect(page.locator("#initialR")).toBeVisible();
  await expect(page.locator("#initialLr")).toBeVisible();
  await expect(page.locator("#initialL")).toBeVisible();
  await expect(page.locator(".equation-label")).toHaveCount(0);
  await expect(page.locator("#luminosityEquations")).toHaveAttribute("data-geometry-mode", "radius-dependent");
  await expect(page.locator("#luminosityEquations")).toHaveAttribute("data-eta-value", "0.89");
  await expect(page.locator("#odeEquations")).toHaveAttribute("data-driver-mode", "h");
  await expect(page.getByRole("heading", { name: "Derived" })).toHaveCount(0);
  await expect(page.locator("#timeLegend")).toContainText("radius");
  await expect(page.locator("#timeLegend")).toContainText("nonadiabatic pressure factor");
  const legendHtml = await page.locator("#timeLegend").innerHTML();
  expect(legendHtml).toContain("R");
  expect(legendHtml).toContain("H");
  const hasPaint = await page.locator("#lightCanvas").evaluate((canvas) => {
    const node = canvas as HTMLCanvasElement;
    const ctx = node.getContext("2d");
    if (!ctx) return false;
    return ctx.getImageData(0, 0, node.width, node.height).data.some((value) => value !== 0);
  });
  expect(hasPaint).toBe(true);
  await page.locator("#variableM").uncheck();
  await expect(page.locator("#luminosityEquations")).toHaveAttribute("data-geometry-mode", "fixed");
  await page.locator("#variableM").check();
  await expect(page.locator("#luminosityEquations")).toHaveAttribute("data-geometry-mode", "radius-dependent");
  const timeLegendHtmlBeforeMSlider = await page.locator("#timeLegend").innerHTML();
  await page.locator("input[aria-label='shell form factor']").evaluate((input) => {
    const slider = input as HTMLInputElement;
    slider.value = "15";
    slider.dispatchEvent(new Event("input", { bubbles: true }));
  });
  await expect(page.locator("#luminosityEquations mjx-container")).not.toHaveCount(0);
  await expect(page.locator("#metrics mjx-container")).not.toHaveCount(0);
  expect(await page.locator("#timeLegend").innerHTML()).toBe(timeLegendHtmlBeforeMSlider);
  await expect(page.locator("#luminosityEquations")).toHaveAttribute("data-eta-value", "0.93");
  await page.locator("input[aria-label='shell form factor']").evaluate((input) => {
    const slider = input as HTMLInputElement;
    slider.value = "3";
    slider.dispatchEvent(new Event("input", { bubbles: true }));
  });
  await expect(page.locator("#luminosityEquations")).toHaveAttribute("data-eta-value", "0.00");
  await page.locator("[data-reset-key='m']").click();
  await expect(page.locator("#luminosityEquations")).toHaveAttribute("data-eta-value", "0.89");
  await page.locator("[data-driver='abs-v']").click();
  await expect(page.locator("#odeEquations")).toHaveAttribute("data-driver-mode", "abs-v");
  await page.locator("[data-driver='h']").click();
  await expect(page.locator("#odeEquations")).toHaveAttribute("data-driver-mode", "h");

  await page.locator("input[aria-label='maximum integration time']").evaluate((input) => {
    const slider = input as HTMLInputElement;
    slider.value = "3";
    slider.dispatchEvent(new Event("input", { bubbles: true }));
  });
  await expect(page.locator("#metrics")).toContainText("1.00e+3", { timeout: 15000 });
  await page.getByRole("button", { name: "DOP853" }).click();
  await expect(page.getByRole("button", { name: "DOP853" })).toHaveClass(/active/);
  await expect(page.locator("#metrics")).toContainText("1.00e+3", { timeout: 15000 });
  await page.getByRole("button", { name: "Final cycles" }).click();
  await expect(page.getByRole("button", { name: "Final cycles" })).toHaveClass(/active/);
  await expect(page.locator("#metrics")).not.toContainText("final cycles");
  await expect(page.locator("#metrics")).not.toContainText("unavailable");

  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download CSV" }).click();
  const download = await downloadPromise;
  const path = await download.path();
  expect(path).toBeTruthy();
  const csv = await readFile(path!, "utf8");
  expect(csv.split(/\r?\n/, 1)[0]).toBe("tau,R,V,H,Uc,Lr,Lc,L");
  expect(pageErrors).toEqual([]);
});
